/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.string.calculator;

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

class AppTest {

  @Test
  @DisplayName("main 테스트")
  void main() {
    String[] args = null;
    String input = "34253678543 - 657788900008887 * 657878921312121";

    InputStream in = new ByteArrayInputStream(input.getBytes());
    System.setIn(in);

    App.main(args);
  }

}
