/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.string.calculator;

import com.string.calculator.output.Category;
import com.string.calculator.output.Format;
import com.string.calculator.output.FormatFactory;
import com.string.calculator.output.web.SpringBootApplication;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.Scanner;
import org.yaml.snakeyaml.Yaml;

public class App {

  public static void main(String[] args) {
    Scanner scanner = new Scanner(System.in);
    System.out.print("num : ");
    String input = "";
    if (scanner.hasNextLine()) {
      input = scanner.nextLine();
    }

    Calculator calculator = new Calculator();
    String result = calculator.calculate(input).getValue();

    System.out.println("출력 포맷을 선택하세요.");
    System.out.println("1. json, 2. xml, 3. plain-text");

    int formatInput = scanner.nextInt();
    Category category = getCategory(formatInput);
    FormatFactory formatFactory = new FormatFactory();
    Format format = formatFactory.create(result, category);
    String outputFormat = format.make();

    System.out.println("출력 위치를 선택하세요.");
    System.out.println("1. 표준 출력, 2. 파일 출력, 3. 웹으로 출력");

    int positionInput = scanner.nextInt();
    if (positionInput == 1) {
      System.out.println("num : " + outputFormat);
    } else if (positionInput == 3) {
      String folder = System.getProperty("user.dir");
      Map<String, Object> data = new HashMap<>();
      data.put("result", outputFormat);

      Yaml yaml = new Yaml();
      try {
        FileWriter writer = new FileWriter(folder + "/application.yml");
        yaml.dump(data, writer);
      } catch (IOException e) {
        e.printStackTrace();
      }
      SpringBootApplication.main(args);
    }

  }

  private static Category getCategory(int formatInput) {
    Category category = null;
    if (formatInput == 1) {
      category = Category.JSON;
    } else if (formatInput == 2) {
      category = Category.XML;
    } else if (formatInput == 3) {
      category = Category.PLAIN;
    }
    return category;
  }

}
