/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.string.calculator;

import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.OutputKeys;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerConfigurationException;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import org.json.simple.JSONObject;
import org.w3c.dom.Document;
import org.w3c.dom.Element;

public class App {

  public static boolean fraction = true;

  public static void main(String[] args) {
    Scanner scanner = new Scanner(System.in);
    System.out.print("num : ");
    String input = "";
    if (scanner.hasNextLine()) {
      input = scanner.nextLine();
    }

    Calculator calculator = new Calculator();
    String result = calculator.calculate(input);

    System.out.println("출력 포맷을 선택하세요.");
    System.out.println("1. json, 2. xml, 3. plain-text");

    OutputFormat outputFormat = new OutputFormat(result);

    int formatInput = scanner.nextInt();
    if (formatInput == 1) {
      outputFormat.json();
    } else if (formatInput == 2) {
      outputFormat.xml();
    } else if (formatInput == 3) {
      outputFormat.plainText();
    }
  }

}
